### ISSUE TITLE
Can you please add the possibility if any clipboard is in a collection (e.g. favorites, English), the option to automatically delete the clipboard at the end of the month is enabled in the settings so that no clipboard is deleted from any collection at the end of the month?

### ISSUE THREAD

**Issue by maxdovbysh** [onmyway133/PastePal#1]
Hi. Thank you for the beautiful PastePal app. I use it daily super often 🙂 

Can you please add the possibility if any clipboard is in a collection (e.g. favorites, English), the option to automatically delete the clipboard at the end of the month is enabled in the settings so that no clipboard is deleted from any collection at the end of the month? I store a lot of important information in collections, and it turns out that when the time expires, they disappear, and images become inactive. 

Can you please implement this (sew it into the logic or add a setting)?

Screenshots: https://www.dropbox.com/sh/fylwd66zmnuse6j/AACBYfL0_xLGQSpphYscOwXya?dl=0

**Comment by onmyway133** [comment]
@maxdovbysh Hi Max, PastePal should not periodically purge clips if they are locked, in a collection or named
