### ISSUE TITLE
"Are you sure you want to quit PastePal" prompt popping up randomly

### ISSUE THREAD

**Issue by razisyed97** [onmyway133/PastePal#10]
**Describe the bug**
Occasional quit dialogue without me doing so: 

<img width="263" alt="image" src="https://github.com/onmyway133/PastePal/assets/6609367/5bf3f906-018f-4b57-83a3-5f74d2a6c05b">

**To Reproduce**
1. Have PastePal open in the background

**Expected behavior**
Not quit unless you're manually quitting. I assume it may be prompting to do in order for it to update, but in that case it should do so in the background.

**Desktop**
 - OS: macOS Sonoma 14.0 but happened on Ventura as well
 - Version: 2.13.0 (143)

**Comment by Delvien** [comment]
I have this same problem. Most times its when resuming from sleep in my experience.

**Comment by onmyway133** [comment]
@razisyed97 @Delvien for now, you can toggle off "Confirm before quitting" in PastePal settings

**Comment by Delvien** [comment]
> @razisyed97 @Delvien for now, you can toggle off "Confirm before quitting" in PastePal settings to get rid of this confirmation that asks to quit.

wouldn’t that just finish quitting it quietly?

**Comment by onmyway133** [comment]
@Delvien right, can you check PastePal latest version 2.13.2 to see if it fixes the issue for you?

**Comment by onmyway133** [comment]
@Delvien sounds good, thanks for checking. I will close this for now, feel free to reopen it again if the issue persists

**Comment by twilsonco** [comment]
I've been experiencing this on my M1 Mac Mini (MacOS 15.1) with v2.16.6(184), but it's always after the machine has sat for a bit. For the last few days, each morning when I first wake up the machine, the "are you sure you want to quit PastePal" dialog will be open. @onmyway133
