### ISSUE TITLE
Ability to Pull Items using Shortcuts on iOS

### ISSUE THREAD

**Issue by kayschab** [onmyway133/PastePal#14]
**Is your feature request related to a problem? Please describe.**
Would like to implement pastepal with shortcuts more often.  

**Describe the solution you'd like**
It would be awesome to be able to pull the items from a certain collection via a shortcut on iOS. For instance either searching a term and getting the resulting items that matched or picking a collection and getting the last X amount of items. 

**Describe alternatives you've considered**
Using the app without shortcuts. It isn't a necessary but other apps allow this. For instance an app called copy'em allows you to search items and pull a certain number from a chosen collection. PastePal has a cleaner keyboard and has kept me. I think it is the better app. But these features would put it over the top. 

**Additional context**
Screenshot of other apps ability in terms of iOS shortcuts![image](https://github.com/onmyway133/PastePal/assets/61208705/b863ea50-cda1-447b-82f6-696790c9752d)

**Comment by onmyway133** [comment]
@kayschab Hi, thanks for the feedback. PastePal now has the Get Item shortcut to get (and configure) which items to fetch.
