### ISSUE TITLE
Scroll Queue as saved text is pasted

### ISSUE THREAD

**Issue by nachosdesign** [onmyway133/PastePal#16]
Currently when pasting items in sequence from the queue, the selected item will move down one item at the time.
The problem is that when the queue is very long, the selected item moves out of view as you are pasting, meaning that you can't really see what you are pasting unless you go to the Queue window and scroll.

I wish that the Queue window will scroll automatically to keep the selected item and a couple of the next items to paste always in view

**Comment by nachosdesign** [comment]
I updated and it’s fixed! Thanks for the latest update, It’s great!!!

**Comment by onmyway133** [comment]
@nachosdesign I will close this issue for now. Feel free to open issue if you face other problems ❤️
