### ISSUE TITLE
Queue window should follow as we move screens

### ISSUE THREAD

**Issue by nachosdesign** [onmyway133/PastePal#18]
PastePal is great! But this is a small issue I have:
**When** using the Queue with multiple desktops and/or having apps in Full Screen view, the Queue window remains on the desktop/app where it was activated.
**This means that**, if I change desktop/app, I have to close the Queue window and open it again on the desired desktop/app.
**I would expect** the Queue window to follow me around as I move desktops/apps, so that I can quickly copy and paste items (this is how Paste does it).

Thanks for all your work! PastePal is great

**Comment by onmyway133** [comment]
@nachosdesign thanks for the feedback, this will be fixed in upcoming release

**Comment by onmyway133** [comment]
@nachosdesign it has been fixed in the latest release. Please check it and let me know if it works for you
