### ISSUE TITLE
Cannot Save image to different filename

### ISSUE THREAD

**Issue by treshed** [onmyway133/PastePal#5]
When I try to save a screenshot, I get the standard name "untitled.png" which I would like to change, so I can save it because there is already a untitled.png in that folder.
When I go into the box to change the name, it does not let me.

**To Reproduce**
Create a screenshot.
Click on Save As in Pastepal.
Save WIndows opens.
Try to change the name of "untitled.png"
Changing folders also does not help with changing the name.

**Expected behavior**
I expect to be able to save the file under another name.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Macos 13.1/13/2
 - Version 2.11.7 (129)

**Comment by onmyway133** [comment]
@treshed thanks for the feedback, I will try to support custom name

**Comment by onmyway133** [comment]
@treshed can you try this again in the latest release 2.12.9 ?

**Comment by onmyway133** [comment]
Glad it works. I will close this issue for now
