### ISSUE TITLE
Slow and laggy compared to paste & pasty

### ISSUE THREAD

**Issue by Ramalama2** [onmyway133/PastePal#6]
MacOS 13.2 Ventura
Macbook Pro 16inch M2 Max

Hi, i would love to use the app, because of the onetime payment compared to paste.
But tbh, pastepal is either extremely slow itself, or there is a bug/incompatibility on Ventura?

If it helps, i could make a slowmotion screen recording, how huge the difference is.
Otherwise even klicking something on that edgewindow/edgeboard or how thats called, is extremely painful.
It either doesn't react at all, or i have to click 2/3 times...
And if it reacts it takes like 500ms-1s.

Paste or Pasty, i tryed both, since pastepal/pasty/paste are all very similar and exactly what im searching.
However paste & pasty work fluidly like lightspeed, they are extremely performant.

Im hoping that this is fixable. I can even help with remote desktop or whatever is needed.
Otherwise i just refunded the money from apple, because it's unusable slow for me, sry.

But what i mean is, if it's possible to fix/improve this app, i would love it! Because paste's yearly payment subscription, is something i try to stay away from.
And Pasty actually works great, but is a bit limited in features 🙈

Cheers

**Comment by Ramalama2** [comment]
> @Ramalama2 thanks for the feedback. Can you help me record a video, I would love to improve the performance further more

Hey, sure, i would love to help!
Im just atm at holidays, without my macbook :-(
But as soon as i get back to home, I'll do a video!

Thank you for the effort!

**Comment by onmyway133** [comment]
@Ramalama2 take your time, enjoy the holidays 🌴

**Comment by Delvien** [comment]
3 week long holiday? I want to live where you live. :)

Any update OP?

**Comment by Ramalama2** [comment]
> 3 week long holiday? I want to live where you live. :)
> 
> Any update OP?

Ill do an update today, in 3-5hours or so 🙈
Actually i camed back last week, just had so much work to catch-up that i forgot this tbh 😂

Thx for the reminder!

**Comment by Ramalama2** [comment]
Fuck i didn't had time today, sorry.
I'll close this topic and reopen it when i did the video🙈

Thanks for the support guys, sry for beeing a bad issuer 🙈
