### ISSUE TITLE
past from history always write "undefined" instead of the selected text.

### ISSUE THREAD

**Issue by megimix** [onmyway133/PastePal#7]
**Describe the bug**
cant paste text, instead of the selected text, it writing "undefined" 

**To Reproduce**
1. select from history, press enter

**Expected behavior**
the selected text is pasted

**Desktop (please complete the following information):**
 - OS: 13.4 (22F66)
 - Version [e.g. 2.12.7 (140)]

**Comment by onmyway133** [comment]
@megimix Hi, have you enabled any Transformation rules? You can check Transformation in PastePal settings

**Comment by talshacharhz** [comment]
You are right, transformation rule.
I don't know what toggled this, but it's very unclear that this check mark can be so critical for the app usage.

Thanks, Tal

**Comment by onmyway133** [comment]
Glad you sorted it out. Transformation is where we can define our own transformation function.
