### ISSUE TITLE
Multi selection

### ISSUE THREAD

**Issue by sebastiencounen** [onmyway133/PastePal#9]
**Describe the bug**
When trying to press shift + down/up arrow, it triggers a search with the following character ''.
When copying multiple elements or "arranger -> move to top", it takes only the last one selected.

**To Reproduce**
1. Open pastepal's sidebar
2. Select 2 items which aren't the first ones
3. Copy them
4. See only the last one selected was brought to the top
5. Press shift + down arrow to select the 2 first items
6. It does not select the below item as before

**Expected behavior**
Whereas it allowed multiselection in the past for pasting or putting on top multiple items at once (by copying them after selection or arrange move to top)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.1
 - Version PastePal 2.12.9

**Comment by onmyway133** [comment]
@sebastiencounen thanks for the feedback, I will check and fix it

**Comment by onmyway133** [comment]
@sebastiencounen hi, these issues should be fixed in the latest release 2.13.0. Let me know if it works for you

**Comment by sebastiencounen** [comment]
@onmyway133 hi, great, thanks. I've tested it and multi select with shift + down/up arrow works great and moving several items to the top as well (by using 'Arrange > Move to top') !

One last thing is: I cannot copy multiple items at the same time (it was possible before if I'm not mistaken). Anyway, it was a great feature I used a lot, and it would be great if it came back 😃

Thank you !

**Comment by onmyway133** [comment]
@sebastiencounen Hi, glad it works 🎉 

You can paste multiple selected clips.
You can also copy multiple selected clips, but depends on how the behaviors of other apps. Some apps can inteprete all the copied clips PastePal send, some like Notes, only accept clips of the same type, like either all text, or all images

**Comment by sebastiencounen** [comment]
@onmyway133 In fact I can paste multiple items by pressing enter after selecting it, my bad. Great, and thank you for the fast reply and fix !!

**Comment by onmyway133** [comment]
@sebastiencounen Nice to know. I will close this issue for now, feel free to open another issue if you have problems. Thanks for using PastePal
